### ISSUE TITLE
Can you read out ENV variables and read the settings file 

### ISSUE THREAD

**Issue by ma-karai** [CobayeGunther/Emby2Jelly#4]
I'd like to dockerize your script, there are some things that would be great maybe you can conditionally read out the ENV variables.
 
Something along this would probably work.
```
# Get environment variables
EMBY_APIKEY = os.getenv('EMBY_APIKEY')
EMBY_URLBASE = os.getenv('EMBY_URLBASE')
JELLY_APIKEY = os.getenv('JELLY_APIKEY')
JELLY_URLBASE = os.getenv('JELLY_URLBASE')
```

**Comment by ma-karai** [comment]
https://github.com/ma-karai/emby2jelly-docker/blob/master/Dockerfile

you can check it out here, it works already, after you edit the settings file and run the API.py manually but, it would be nice if i just can run the docker container with the ENV variables and have it do the rest by itself

**Comment by CobayeGunther** [comment]
Yes of course, I want to add ability to define these variables in command line argument too

**Comment by CobayeGunther** [comment]
added in commit ffb949093b2cc80917c112691a34e2a19b040846 branch docker-friendly
I tested with shell environment variables, can you tell me if it i good for you ? ( I'm not much familiar with docker )

**Comment by ma-karai** [comment]
yeah i'll give it a try :D

**Comment by ma-karai** [comment]
works btw, i have not done the final run but. if you run my docker container like the following it should just transfer emby to jelly 



```
docker run -e EMBY_APIKEY=aaaabbbbbbbcccccccccccccdddddddd \
           -e EMBY_URLBASE=http://127.0.0.1:8096/ \
           -e JELLY_APIKEY=eeeeeeeeeeeeeeeffffffffffffffffggggggggg \
           -e JELLY_URLBASE=http://127.0.0.2:8096/ \
           -e NEW_USER_PWD=pls_change_your_pwd_user_123afed makarai/emby2jelly-docker
```

**Comment by LLDaLastDon** [comment]
@ma-karai I ran the docker and got this at the end of the run

/root/start.sh: line 18: unexpected EOF while looking for matching `"'
/root/start.sh: line 19: syntax error: unexpected end of file

**Comment by ma-karai** [comment]
> @ma-karai I ran the docker and got this at the end of the run
> 
> /root/start.sh: line 18: unexpected EOF while looking for matching `"'
> /root/start.sh: line 19: syntax error: unexpected end of file

I'll have to get back to you on that.

**Comment by LLDaLastDon** [comment]
> 
> 
> > @ma-karai I ran the docker and got this at the end of the run
> > /root/start.sh: line 18: unexpected EOF while looking for matching `"'
> > /root/start.sh: line 19: syntax error: unexpected end of file
> 
> I'll have to get back to you on that.

I fixed it and submitted a pull request to your repo.

**Comment by ma-karai** [comment]
thanks for everything!
