### ISSUE TITLE
Migrate Collections

### ISSUE THREAD

**Issue by supernovajm** [CobayeGunther/Emby2Jelly#6]
Please add the ability to migrate collections

**Comment by CobayeGunther** [comment]
collections are like movies or tv shows inside your emby/jellyfin server, libraries.
This script just send watched statuses of items inside these collections. 

These items are showing inside your movie library, but if you have [TMDb Box Sets plugin ](https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets/wiki/TMDb-Box-Sets)on your target server, they will be grouped into collections if needed
