### ISSUE TITLE
Error Looking For Users?

### ISSUE THREAD

**Issue by lemkeant** [CobayeGunther/Emby2Jelly#8]
Im on Windows, and was hoping to pull off the migration from Emby to Jellyfin for my watched files. 

I can read off of Emby just fine and create a file. However, when it tries to move to Jellyfin, I'm receiving an error about users? Not sure? I'm moving from the same user to same user, only 1 user available in both Emby and Jellyfin

> Traceback (most recent call last):
>  
>  File "APImain.py", line 498, in <module>
>     jelly(newUser_pw)
>   File "APImain.py", line 413, in jelly
>     jellyUsers = jelly_get_users_list()
>   File "APImain.py", line 187, in jelly_get_users_list
>     return "error : " + json.loads(response.content.decode('utf-8'))
>   File "C:\Users\...\Python38\lib\json\__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "C:\Users\...\Python38\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Users\...\Python38\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lemkeant** [comment]
interesting enough, I see this in my Jellyfin console when running this? Did the location move?

> [24] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Unable to find the specified file. URL: http://192.168.1.39:8096/jellyfin/Users

**Comment by pcartwright81** [comment]
Using the current Jellyfin at https://repo.jellyfin.org/releases/server/windows/stable my jellyfin api is still at http://127.0.0.1:8096/emby/  I moved the emby to http://127.0.0.1:8097/emby/.  This is confirmed by going to http://localhost:8096/swagger.json and looking at the api.

I set my JELLY_URLBASE = http://127.0.0.1:8096/emby/

**Comment by lemkeant** [comment]
I was trying to run it remotely and not need to install Python on my server (hence 192.168.1.39). However, im just having too many issues
